export const CareersContent = {
  slug: "careers",
  metadata: {
    url: "https://clickmastersdigitalmarketing.com/careers/",
    seoTitle: "Careers at Clickmasters — Remote Digital Marketing Roles for Serious Specialists | Clickmasters",
    metaDescription: "Remote digital marketing careers at Clickmasters. SEO, paid media, content strategy, B2B marketing, and account management roles. Work across UK, USA, UAE, Pakistan, Canada & Australia.",
    schema: "JobPosting + Organization",
    author: "Amjad Khan, CEO — Clickmasters Digital Marketing",
    primaryKeyword: "digital marketing jobs remote",
    volume: "8,100/mo",
    cpc: "$4.80",
    wordCount: "~2,200 words",
    internalLinks: "/about-us/, /our-team/, /contact-us/",
  },
  hero: {
    tag: "[ Careers ] Join Clickmasters",
    title: "Careers at Clickmasters",
    titleHighlight: "— Remote Digital Marketing Roles for Serious Specialists",
    subtitle: "",
    description: "Clickmasters Digital Marketing is a growing digital marketing and software agency serving businesses in the USA, UK, UAE, Pakistan, Canada, and Australia. We are building a team of exceptional specialists — practitioners who have chosen digital marketing as a serious profession, who go deep in their disciplines rather than wide, and who measure their professional success by the commercial outcomes they produce for clients rather than the activity they generate.",
    stats: [
      { k: "6", v: "Markets served" },
      { k: "8,100/mo", v: "Remote job searches" },
      { k: "100%", v: "Remote-first" },
      { k: "5+", v: "Open positions" },
    ],
  },
  intro: {
    problem: [
      { text: "We hire fully remotely. Our team operates across multiple time zones — the UK, UAE, Pakistan, USA, and Canada — and our remote-first model is not a pandemic accommodation: ", type: "normal" },
      { text: "it is the operational foundation that makes our global delivery model commercially viable", type: "highlight" },
      { text: " and that enables us to hire the best specialists in each discipline rather than the best specialists within commuting distance of any single office.", type: "normal" }
    ],
    solution: "If you are an exceptional digital marketing specialist — with genuine expertise in your discipline, a commercial orientation that makes you think in terms of client outcomes, and the communication ability to explain complex performance data clearly to non-specialist audiences — we want to hear from you.",
    promise: "",
  },
  workCulture: {
    title: "What It Is Like",
    titleHighlight: "to Work at Clickmasters",
    items: [
      {
        icon: "Target",
        title: "Specialists, Not Generalists",
        body: "Clickmasters hires specialists. We do not hire 'digital marketers' who can do a bit of everything at a mediocre level. We hire SEO practitioners who understand how Google's ranking algorithm actually works. We hire paid media managers who understand auction dynamics, quality score mechanics, and conversion rate optimisation. If you are a genuine specialist, you will be surrounded by other genuine specialists, evaluated on commercial outcomes rather than hours logged.",
      },
      {
        icon: "DollarSign",
        title: "Commercial Accountability",
        body: "Every programme we manage is evaluated against the qualified leads it generates, the revenue it produces, and the commercial value it creates for clients. Our team members are evaluated against the same standards: not the number of articles written, campaigns launched, or reports produced — but the commercial outcomes those activities produce. This is more demanding, but more satisfying for those who want to make a commercial difference.",
      },
      {
        icon: "Globe",
        title: "Multi-Market Exposure",
        body: "Working at Clickmasters means working across multiple markets simultaneously — the UK, USA, UAE, Pakistan, Canada, and Australia. You will work on legal SEO for a New York law firm, e-commerce marketing for a UK DTC brand, B2B LinkedIn for a Dubai professional services firm, and content strategy for an Australian healthcare practice — sometimes in the same week.",
      },
      {
        icon: "Home",
        title: "Genuine Remote Culture",
        body: "Our remote model is genuinely remote — not a hybrid arrangement where remote workers are second-class citizens. We have no office. Everyone is remote. Our communication culture is built around asynchronous-first communication: written briefs, documented decisions, and the expectation that work is understood from written communication rather than verbal instruction.",
      },
      {
        icon: "TrendingUp",
        title: "Growth and Development",
        body: "We invest in team development. Every team member has a professional development budget for courses, certifications, tools, and platform-specific training that keeps specialist knowledge current. The digital marketing discipline changes continuously — algorithm updates, platform changes, new channels — and we support the continuous learning that keeps our team's capabilities at the standard our clients deserve.",
      },
    ],
  },
  openPositions: [
    {
      id: "seo-specialist",
      title: "SEO Specialist",
      type: "Remote (Multiple Markets)",
      description: "We are looking for an experienced SEO specialist with hands-on technical and content SEO expertise for the UK, US, and/or Australian markets.",
      responsibilities: [
        "Conduct comprehensive technical SEO audits",
        "Develop keyword strategies for commercial and informational content",
        "Produce and optimise service pages and content marketing assets",
        "Build link acquisition through digital PR and industry publication outreach",
        "Measure and report on organic search performance against commercial outcome metrics",
      ],
      requirements: [
        "Minimum 3 years of SEO experience with demonstrable organic ranking results",
        "Technical SEO expertise including Core Web Vitals, crawl optimisation, and structured data",
        "Experience with at least one major SEO toolset (Ahrefs, Semrush, Moz)",
        "Strong written English with the ability to produce content that ranks and converts",
        "Market-specific expertise in at least one of our six markets preferred",
      ],
    },
    {
      id: "paid-media-manager",
      title: "Paid Media Manager",
      type: "Remote (Google Ads / Meta Ads)",
      description: "We are looking for a paid media manager with expertise in Google Ads and/or Meta Ads for commercial lead generation and e-commerce programmes.",
      responsibilities: [
        "Build, manage, and optimise Google Ads campaigns (Search, Shopping, Performance Max, Display, YouTube)",
        "Manage Meta Ads campaigns across Facebook and Instagram for lead generation and e-commerce",
        "Conduct ongoing conversion rate optimisation on landing pages",
        "Report on paid performance against commercial metrics (CPL, ROAS, revenue attributed)",
      ],
      requirements: [
        "Minimum 3 years of paid media management experience",
        "Current Google Ads certification (Search required; Shopping and Performance Max preferred)",
        "Experience managing advertising budgets above $10,000/month",
        "Strong analytical capability with GA4 and platform-native analytics",
        "E-commerce and lead generation campaign experience",
      ],
    },
    {
      id: "content-strategist",
      title: "Content Strategist and Writer",
      type: "Remote",
      description: "We are looking for a content strategist and writer with the ability to produce genuinely expert-level content across multiple sectors and markets.",
      responsibilities: [
        "Develop content strategies for client SEO programmes",
        "Write and edit long-form service pages, thought leadership articles, and topic authority content",
        "Produce content that meets E-E-A-T standards for YMYL sectors (legal, healthcare, financial services)",
        "Ensure content compliance with sector-specific regulatory frameworks (GDC, SRA, FCA, HIPAA, AHPRA)",
      ],
      requirements: [
        "Minimum 3 years of SEO content writing experience",
        "Strong track record of producing content that ranks for commercial search terms",
        "Ability to write across multiple disciplines and adopt appropriate voice and tone",
        "Familiarity with UK and/or US regulatory frameworks for healthcare, legal, or financial services preferred",
        "Exceptional written English",
      ],
    },
    {
      id: "b2b-specialist",
      title: "B2B Digital Marketing Specialist",
      type: "Remote (LinkedIn and Content)",
      description: "We are looking for a B2B digital marketing specialist with specific expertise in LinkedIn marketing, thought leadership content production, and B2B demand generation.",
      responsibilities: [
        "Develop and execute LinkedIn thought leadership programmes for client founders and senior leaders",
        "Manage LinkedIn Ads campaigns targeting specific B2B buyer personas",
        "Produce technical and professional content that builds authority with B2B buyer communities",
        "Measure and report on B2B programme performance against pipeline and revenue metrics",
      ],
      requirements: [
        "Minimum 3 years of B2B digital marketing experience with specific LinkedIn expertise",
        "Ability to ghostwrite thought leadership content that sounds genuinely expert in technical domains",
        "Experience with LinkedIn Campaign Manager and LinkedIn Sales Navigator",
        "Familiarity with B2B sales cycles and the commercial context of B2B marketing investment",
      ],
    },
    {
      id: "account-manager",
      title: "Account Manager — Client Services",
      type: "Remote",
      description: "We are looking for an account manager with commercial orientation, digital marketing knowledge, and communication skills to manage client relationships.",
      responsibilities: [
        "Manage a portfolio of client relationships as the primary client point of contact",
        "Brief specialist teams on client objectives and translate feedback into actionable adjustments",
        "Produce and present monthly performance reports to clients",
        "Identify upsell and expansion opportunities within existing relationships",
        "Ensure client retention through exceptional service quality and commercial outcome delivery",
      ],
      requirements: [
        "Minimum 3 years of agency account management experience",
        "Genuine understanding of SEO, paid advertising, and at least two other digital marketing disciplines",
        "Strong client communication skills — ability to explain complex performance data in commercial terms",
        "Commercial orientation — you think in terms of client ROI, not activity delivered",
      ],
    },
  ],
  hiringProcess: {
    title: "Our Hiring",
    titleHighlight: "Process",
    steps: [
      {
        step: "1",
        title: "Application Review",
        description: "We review every application we receive. We do not use automated screening for initial review — every application is read by a member of our team. Applications that clearly demonstrate specialist expertise, commercial orientation, and strong written communication advance to the next stage.",
      },
      {
        step: "2",
        title: "Skills Assessment",
        description: "Shortlisted candidates complete a discipline-specific skills assessment — a realistic task that reflects the actual work the role involves. SEO candidates conduct a mini-audit or keyword strategy exercise. Paid media candidates build a campaign structure or audit an existing account. Content candidates produce a writing sample to a brief. We pay for completed assessments that require significant time — we do not use skills assessments as a way to obtain free work.",
      },
      {
        step: "3",
        title: "Interview",
        description: "Candidates who perform well on the skills assessment are invited to a video interview with the team lead for their discipline and, typically, a senior member of the account management team. We are looking for the specific combination of technical depth, commercial orientation, and communication clarity that defines the Clickmasters team standard.",
      },
      {
        step: "4",
        title: "Offer and Onboarding",
        description: "Successful candidates receive a transparent offer that documents the role, compensation, performance expectations, and growth trajectory. Onboarding is structured around the specific tools, processes, and client contexts the new team member will work on — not a generic induction programme.",
      },
    ],
  },
  apply: {
    title: "Ready to Apply?",
    description: "If you are a genuine specialist who wants to work in a remote-first, commercially accountable, multi-market digital marketing environment — we want to hear from you.",
    contactLink: "https://clickmastersdigitalmarketing.com/contact-us/",
    aboutLink: "https://clickmastersdigitalmarketing.com/about-us/",
    teamLink: "https://clickmastersdigitalmarketing.com/our-team/",
    instructions: "Include in your application: your specific discipline and years of experience, the markets you have worked in, one or two examples of commercial outcomes you have produced for clients (specific metrics preferred), and your preferred working arrangement (hours, time zone, availability).",
  },
  footer: {
    company: "Clickmasters Digital Marketing",
    url: "https://clickmastersdigitalmarketing.com",
    email: "marketing@clickmastersdigitalmarketing.com",
    careersEmail: "marketing@clickmastersdigitalmarketing.com",
    regions: "USA · UK · UAE · Pakistan · Canada · Australia",
    author: "Amjad Khan — CEO | Remote-first | 2026",
  },
};